name: peak_path_iot
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bottom_navy_bar: ^6.0.0
  intl: ^0.18.1
  # flutter_map_marker_cluster: ^1.3.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/gambar/home.png
    - assets/gambar/header.jpg
    - assets/gambar/pendaki.jpg
    - assets/gambar/akun.png
    - assets/gambar/akun2.png


    

  fonts:
    - family: great
      fonts: # Lokasi font di dalam direktori 'assets'
        - asset: assets/font/FrederickatheGreat-Regular.ttf
